name: Lint

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master


defaults:
  run:
    shell: bash -el {0}

jobs:
  pre-commit-checks:
    name: "Linux - pre-commit hooks"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: Install Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Run pre-commit checks
        uses: pre-commit/action@v3.0.0
