name: Test

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python:
          - "3.7"
          - "3.10"

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3
        with:
          python-version: "${{ matrix.python }}"

      - name: Install dependencies
        run: |
          pip install -r requirements-test.txt codecov

      - name: Install editable package
        run: |
          pip install -e .

      - name: Run tests
        run: |
          conda-mirror -h
          coverage run --concurrency=multiprocessing run_tests.py
          coverage combine
          coverage report -m
